import sharp from 'sharp'
import pngToIco from 'png-to-ico'
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const build = join(root, 'build')
mkdirSync(build, { recursive: true })
const svg = readFileSync(join(build, 'icon.svg'))

async function main() {
  // High-density master render, then downscale for crisp small sizes.
  const master = await sharp(svg, { density: 384 }).resize(1024, 1024).png().toBuffer()
  writeFileSync(join(build, 'icon.png'), master)
  writeFileSync(join(build, 'icon-preview-256.png'), await sharp(master).resize(256, 256).png().toBuffer())

  const sizes = [256, 128, 64, 48, 32, 16]
  const buffers = await Promise.all(sizes.map((s) => sharp(master).resize(s, s).png().toBuffer()))
  writeFileSync(join(build, 'icon.ico'), await pngToIco(buffers))

  // Embed a small icon as a data URL so the tray + dev window icon work in
  // both dev and packaged builds without depending on a file path.
  const small = await sharp(master).resize(64, 64).png().toBuffer()
  const dataUrl = 'data:image/png;base64,' + small.toString('base64')
  writeFileSync(
    join(root, 'src', 'main', 'trayIcon.ts'),
    `// Auto-generated by scripts/make-icons.mjs — do not edit by hand.\nexport const APP_ICON_DATA_URL =\n  '${dataUrl}'\n`
  )

  console.log('Generated build/icon.png, build/icon.ico, build/icon-preview-256.png, src/main/trayIcon.ts')
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
